### ISSUE TITLE
IOUtils not found

### ISSUE THREAD

**Issue by sigman78** [bitstadium/BakeBread#2]
error: cannot find symbol 'IOUtils' class not found, while trying to compile with ant and oraclejdk

**Comment by dryganets** [comment]
@paul-mc-arrow, could you take a look?

I'm not sure if anyone supports this repository now when we both left Microsoft.

I see it has been moved to HockeyApp from Skype which is probably a good sign  :)

**Comment by dryganets** [comment]
@sigman78 ,
My only guess why the IOUtils could be not found is that you are using the jdk which doesn't have sun internal classes.

`sun.misc.IOUtils` I guess is part of the oracle jdk, but likely missing in the openjdk.

I have no background on why @paul-mc-arrow used the internal classes though, I think it  could be moved to something more portable :)

**Comment by sigman78** [comment]
@dryganets HockeyApp is acquired by the Microsoft under the name of AppCenter so I guess it doesn't make a huge difference)

**Comment by dryganets** [comment]
Nor me not @paul-mc-arrow are working at Microsoft anymore.
This project was supported by Skype originally.
It was an internal tool for debugging device specific native issues.

The fact that it got moved to HockeyApp makes difference because in this case there is at least a slight chance that you will get any support as I don't think anyone at Skype is interested in this tool now.
I don't remember we needed this tool since we moved to react-native for mobile.

Anyway, you could try to hook the corresponding code from the apache commons library, it should be trivial to use it.

Another option will be to use jdk 7 from Oracle or OpenJdk 8.
They seems to have corresponding class.

I surprised someone in community has interest in this project as it is supper low level tool designed for hopeless cases like targeting the Linux kernel issues or dealing with device specific issues.

**Comment by dryganets** [comment]
You could refer to this implementation:
https://github.com/JetBrains/jdk8u_jdk/commit/5e7b05bf6ddfdb49ceee54ce112253ed795d68b6
